// Dados do IBGE para Minas Gerais, usados nos filtros da empresa.
export const cidadesMg = [
  'Abadia dos Dourados',
  'Abaeté',
  'Abre Campo',
  'Acaiaca',
  'Açucena',
  'Água Boa',
  'Água Comprida',
  'Aguanil',
  'Águas Formosas',
  'Águas Vermelhas',
  'Aimorés',
  'Aiuruoca',
  'Alagoa',
  'Albertina',
  'Além Paraíba',
  'Alfenas',
  'Alfredo Vasconcelos',
  'Almenara',
  'Alpercata',
  'Alpinópolis',
  'Alterosa',
  'Alto Caparaó',
  'Alto Jequitibá',
  'Alto Rio Doce',
  'Alvarenga',
  'Alvinópolis',
  'Alvorada de Minas',
  'Amparo do Serra',
  'Andradas',
  'Andrelândia',
  'Angelândia',
  'Antônio Carlos',
  'Antônio Dias',
  'Antônio Prado de Minas',
  'Araçaí',
  'Aracitaba',
  'Araçuaí',
  'Araguari',
  'Arantina',
  'Araponga',
  'Araporã',
  'Arapuá',
  'Araújos',
  'Araxá',
  'Arceburgo',
  'Arcos',
  'Areado',
  'Argirita',
  'Aricanduva',
  'Arinos',
  'Astolfo Dutra',
  'Ataléia',
  'Augusto de Lima',
  'Baependi',
  'Baldim',
  'Bambuí',
  'Bandeira',
  'Bandeira do Sul',
  'Barão de Cocais',
  'Barão do Monte Alto',
  'Barbacena',
  'Barra Longa',
  'Barroso',
  'Bela Vista de Minas',
  'Belmiro Braga',
  'Belo Horizonte',
  'Belo Oriente',
  'Belo Vale',
  'Berilo',
  'Berizal',
  'Bertópolis',
  'Betim',
  'Bias Fortes',
  'Bicas',
  'Biquinhas',
  'Boa Esperança',
  'Bocaina de Minas',
  'Bocaiúva',
  'Bom Despacho',
  'Bom Jardim de Minas',
  'Bom Jesus da Penha',
  'Bom Jesus do Amparo',
  'Bom Jesus do Galho',
  'Bom Repouso',
  'Bom Sucesso',
  'Bonfim',
  'Bonfinópolis de Minas',
  'Bonito de Minas',
  'Borda da Mata',
  'Botelhos',
  'Botumirim',
  'Brás Pires',
  'Brasilândia de Minas',
  'Brasília de Minas',
  'Braúnas',
  'Brazópolis',
  'Brumadinho',
  'Bueno Brandão',
  'Buenópolis',
  'Bugre',
  'Buritis',
  'Buritizeiro',
  'Cabeceira Grande',
  'Cabo Verde',
  'Cachoeira da Prata',
  'Cachoeira de Minas',
  'Cachoeira de Pajeú',
  'Cachoeira Dourada',
  'Caetanópolis',
  'Caeté',
  'Caiana',
  'Cajuri',
  'Caldas',
  'Camacho',
  'Camanducaia',
  'Cambuí',
  'Cambuquira',
  'Campanário',
  'Campanha',
  'Campestre',
  'Campina Verde',
  'Campo Azul',
  'Campo Belo',
  'Campo do Meio',
  'Campo Florido',
  'Campos Altos',
  'Campos Gerais',
  'Cana Verde',
  'Canaã',
  'Canápolis',
  'Candeias',
  'Cantagalo',
  'Caparaó',
  'Capela Nova',
  'Capelinha',
  'Capetinga',
  'Capim Branco',
  'Capinópolis',
  'Capitão Andrade',
  'Capitão Enéas',
  'Capitólio',
  'Caputira',
  'Caraí',
  'Caranaíba',
  'Carandaí',
  'Carangola',
  'Caratinga',
  'Carbonita',
  'Careaçu',
  'Carlos Chagas',
  'Carmésia',
  'Carmo da Cachoeira',
  'Carmo da Mata',
  'Carmo de Minas',
  'Carmo do Cajuru',
  'Carmo do Paranaíba',
  'Carmo do Rio Claro',
  'Carmópolis de Minas',
  'Carneirinho',
  'Carrancas',
  'Carvalhópolis',
  'Carvalhos',
  'Casa Grande',
  'Cascalho Rico',
  'Cássia',
  'Cataguases',
  'Catas Altas',
  'Catas Altas da Noruega',
  'Catuji',
  'Catuti',
  'Caxambu',
  'Cedro do Abaeté',
  'Central de Minas',
  'Centralina',
  'Chácara',
  'Chalé',
  'Chapada do Norte',
  'Chapada Gaúcha',
  'Chiador',
  'Cipotânea',
  'Claraval',
  'Claro dos Poções',
  'Cláudio',
  'Coimbra',
  'Coluna',
  'Comendador Gomes',
  'Comercinho',
  'Conceição da Aparecida',
  'Conceição da Barra de Minas',
  'Conceição das Alagoas',
  'Conceição das Pedras',
  'Conceição de Ipanema',
  'Conceição do Mato Dentro',
  'Conceição do Pará',
  'Conceição do Rio Verde',
  'Conceição dos Ouros',
  'Cônego Marinho',
  'Confins',
  'Congonhal',
  'Congonhas',
  'Congonhas do Norte',
  'Conquista',
  'Conselheiro Lafaiete',
  'Conselheiro Pena',
  'Consolação',
  'Contagem',
  'Coqueiral',
  'Coração de Jesus',
  'Cordisburgo',
  'Cordislândia',
  'Corinto',
  'Coroaci',
  'Coromandel',
  'Coronel Fabriciano',
  'Coronel Murta',
  'Coronel Pacheco',
  'Coronel Xavier Chaves',
  'Córrego Danta',
  'Córrego do Bom Jesus',
  'Córrego Fundo',
  'Córrego Novo',
  'Couto de Magalhães de Minas',
  'Crisólita',
  'Cristais',
  'Cristália',
  'Cristiano Otoni',
  'Cristina',
  'Crucilândia',
  'Cruzeiro da Fortaleza',
  'Cruzília',
  'Cuparaque',
  'Curral de Dentro',
  'Curvelo',
  'Datas',
  'Delfim Moreira',
  'Delfinópolis',
  'Delta',
  'Descoberto',
  'Desterro de Entre Rios',
  'Desterro do Melo',
  'Diamantina',
  'Diogo de Vasconcelos',
  'Dionísio',
  'Divinésia',
  'Divino',
  'Divino das Laranjeiras',
  'Divinolândia de Minas',
  'Divinópolis',
  'Divisa Alegre',
  'Divisa Nova',
  'Divisópolis',
  'Dom Bosco',
  'Dom Cavati',
  'Dom Joaquim',
  'Dom Silvério',
  'Dom Viçoso',
  'Dona Euzébia',
  'Dores de Campos',
  'Dores de Guanhães',
  'Dores do Indaiá',
  'Dores do Turvo',
  'Doresópolis',
  'Douradoquara',
  'Durandé',
  'Elói Mendes',
  'Engenheiro Caldas',
  'Engenheiro Navarro',
  'Entre Folhas',
  'Entre Rios de Minas',
  'Ervália',
  'Esmeraldas',
  'Espera Feliz',
  'Espinosa',
  'Espírito Santo do Dourado',
  'Estiva',
  'Estrela Dalva',
  'Estrela do Indaiá',
  'Estrela do Sul',
  'Eugenópolis',
  'Ewbank da Câmara',
  'Extrema',
  'Fama',
  'Faria Lemos',
  'Felício dos Santos',
  'Felisburgo',
  'Felixlândia',
  'Fernandes Tourinho',
  'Ferros',
  'Fervedouro',
  'Florestal',
  'Formiga',
  'Formoso',
  'Fortaleza de Minas',
  'Fortuna de Minas',
  'Francisco Badaró',
  'Francisco Dumont',
  'Francisco Sá',
  'Franciscópolis',
  'Frei Gaspar',
  'Frei Inocêncio',
  'Frei Lagonegro',
  'Fronteira',
  'Fronteira dos Vales',
  'Fruta de Leite',
  'Frutal',
  'Funilândia',
  'Galiléia',
  'Gameleiras',
  'Glaucilândia',
  'Goiabeira',
  'Goianá',
  'Gonçalves',
  'Gonzaga',
  'Gouveia',
  'Governador Valadares',
  'Grão Mogol',
  'Grupiara',
  'Guanhães',
  'Guapé',
  'Guaraciaba',
  'Guaraciama',
  'Guaranésia',
  'Guarani',
  'Guarará',
  'Guarda-Mor',
  'Guaxupé',
  'Guidoval',
  'Guimarânia',
  'Guiricema',
  'Gurinhatã',
  'Heliodora',
  'Iapu',
  'Ibertioga',
  'Ibiá',
  'Ibiaí',
  'Ibiracatu',
  'Ibiraci',
  'Ibirité',
  'Ibitiúra de Minas',
  'Ibituruna',
  'Icaraí de Minas',
  'Igarapé',
  'Igaratinga',
  'Iguatama',
  'Ijaci',
  'Ilicínea',
  'Imbé de Minas',
  'Inconfidentes',
  'Indaiabira',
  'Indianópolis',
  'Ingaí',
  'Inhapim',
  'Inhaúma',
  'Inimutaba',
  'Ipaba',
  'Ipanema',
  'Ipatinga',
  'Ipiaçu',
  'Ipuiúna',
  'Iraí de Minas',
  'Itabira',
  'Itabirinha',
  'Itabirito',
  'Itacambira',
  'Itacarambi',
  'Itaguara',
  'Itaipé',
  'Itajubá',
  'Itamarandiba',
  'Itamarati de Minas',
  'Itambacuri',
  'Itambé do Mato Dentro',
  'Itamogi',
  'Itamonte',
  'Itanhandu',
  'Itanhomi',
  'Itaobim',
  'Itapagipe',
  'Itapecerica',
  'Itapeva',
  'Itatiaiuçu',
  'Itaú de Minas',
  'Itaúna',
  'Itaverava',
  'Itinga',
  'Itueta',
  'Ituiutaba',
  'Itumirim',
  'Iturama',
  'Itutinga',
  'Jaboticatubas',
  'Jacinto',
  'Jacuí',
  'Jacutinga',
  'Jaguaraçu',
  'Jaíba',
  'Jampruca',
  'Janaúba',
  'Januária',
  'Japaraíba',
  'Japonvar',
  'Jeceaba',
  'Jenipapo de Minas',
  'Jequeri',
  'Jequitaí',
  'Jequitibá',
  'Jequitinhonha',
  'Jesuânia',
  'Joaíma',
  'Joanésia',
  'João Monlevade',
  'João Pinheiro',
  'Joaquim Felício',
  'Jordânia',
  'José Gonçalves de Minas',
  'José Raydan',
  'Josenópolis',
  'Juatuba',
  'Juiz de Fora',
  'Juramento',
  'Juruaia',
  'Juvenília',
  'Ladainha',
  'Lagamar',
  'Lagoa da Prata',
  'Lagoa dos Patos',
  'Lagoa Dourada',
  'Lagoa Formosa',
  'Lagoa Grande',
  'Lagoa Santa',
  'Lajinha',
  'Lambari',
  'Lamim',
  'Laranjal',
  'Lassance',
  'Lavras',
  'Leandro Ferreira',
  'Leme do Prado',
  'Leopoldina',
  'Liberdade',
  'Lima Duarte',
  'Limeira do Oeste',
  'Lontra',
  'Luisburgo',
  'Luislândia',
  'Luminárias',
  'Luz',
  'Machacalis',
  'Machado',
  'Madre de Deus de Minas',
  'Malacacheta',
  'Mamonas',
  'Manga',
  'Manhuaçu',
  'Manhumirim',
  'Mantena',
  'Mar de Espanha',
  'Maravilhas',
  'Maria da Fé',
  'Mariana',
  'Marilac',
  'Mário Campos',
  'Maripá de Minas',
  'Marliéria',
  'Marmelópolis',
  'Martinho Campos',
  'Martins Soares',
  'Mata Verde',
  'Materlândia',
  'Mateus Leme',
  'Mathias Lobato',
  'Matias Barbosa',
  'Matias Cardoso',
  'Matipó',
  'Mato Verde',
  'Matozinhos',
  'Matutina',
  'Medeiros',
  'Medina',
  'Mendes Pimentel',
  'Mercês',
  'Mesquita',
  'Minas Novas',
  'Minduri',
  'Mirabela',
  'Miradouro',
  'Miraí',
  'Miravânia',
  'Moeda',
  'Moema',
  'Monjolos',
  'Monsenhor Paulo',
  'Montalvânia',
  'Monte Alegre de Minas',
  'Monte Azul',
  'Monte Belo',
  'Monte Carmelo',
  'Monte Formoso',
  'Monte Santo de Minas',
  'Monte Sião',
  'Montes Claros',
  'Montezuma',
  'Morada Nova de Minas',
  'Morro da Garça',
  'Morro do Pilar',
  'Munhoz',
  'Muriaé',
  'Mutum',
  'Muzambinho',
  'Nacip Raydan',
  'Nanuque',
  'Naque',
  'Natalândia',
  'Natércia',
  'Nazareno',
  'Nepomuceno',
  'Ninheira',
  'Nova Belém',
  'Nova Era',
  'Nova Lima',
  'Nova Módica',
  'Nova Ponte',
  'Nova Porteirinha',
  'Nova Resende',
  'Nova Serrana',
  'Nova União',
  'Novo Cruzeiro',
  'Novo Oriente de Minas',
  'Novorizonte',
  'Olaria',
  'Olhos-d\'Água',
  'Olímpio Noronha',
  'Oliveira',
  'Oliveira Fortes',
  'Onça de Pitangui',
  'Oratórios',
  'Orizânia',
  'Ouro Branco',
  'Ouro Fino',
  'Ouro Preto',
  'Ouro Verde de Minas',
  'Padre Carvalho',
  'Padre Paraíso',
  'Pai Pedro',
  'Paineiras',
  'Pains',
  'Paiva',
  'Palma',
  'Palmópolis',
  'Papagaios',
  'Pará de Minas',
  'Paracatu',
  'Paraguaçu',
  'Paraisópolis',
  'Paraopeba',
  'Passa Quatro',
  'Passa Tempo',
  'Passa Vinte',
  'Passabém',
  'Passos',
  'Patis',
  'Patos de Minas',
  'Patrocínio',
  'Patrocínio do Muriaé',
  'Paula Cândido',
  'Paulistas',
  'Pavão',
  'Peçanha',
  'Pedra Azul',
  'Pedra Bonita',
  'Pedra do Anta',
  'Pedra do Indaiá',
  'Pedra Dourada',
  'Pedralva',
  'Pedras de Maria da Cruz',
  'Pedrinópolis',
  'Pedro Leopoldo',
  'Pedro Teixeira',
  'Pequeri',
  'Pequi',
  'Perdigão',
  'Perdizes',
  'Perdões',
  'Periquito',
  'Pescador',
  'Piau',
  'Piedade de Caratinga',
  'Piedade de Ponte Nova',
  'Piedade do Rio Grande',
  'Piedade dos Gerais',
  'Pimenta',
  'Pingo-d\'Água',
  'Pintópolis',
  'Piracema',
  'Pirajuba',
  'Piranga',
  'Piranguçu',
  'Piranguinho',
  'Pirapetinga',
  'Pirapora',
  'Piraúba',
  'Pitangui',
  'Piumhi',
  'Planura',
  'Poço Fundo',
  'Poços de Caldas',
  'Pocrane',
  'Pompéu',
  'Ponte Nova',
  'Ponto Chique',
  'Ponto dos Volantes',
  'Porteirinha',
  'Porto Firme',
  'Poté',
  'Pouso Alegre',
  'Pouso Alto',
  'Prados',
  'Prata',
  'Pratápolis',
  'Pratinha',
  'Presidente Bernardes',
  'Presidente Juscelino',
  'Presidente Kubitschek',
  'Presidente Olegário',
  'Prudente de Morais',
  'Quartel Geral',
  'Queluzito',
  'Raposos',
  'Raul Soares',
  'Recreio',
  'Reduto',
  'Resende Costa',
  'Resplendor',
  'Ressaquinha',
  'Riachinho',
  'Riacho dos Machados',
  'Ribeirão das Neves',
  'Ribeirão Vermelho',
  'Rio Acima',
  'Rio Casca',
  'Rio do Prado',
  'Rio Doce',
  'Rio Espera',
  'Rio Manso',
  'Rio Novo',
  'Rio Paranaíba',
  'Rio Pardo de Minas',
  'Rio Piracicaba',
  'Rio Pomba',
  'Rio Preto',
  'Rio Vermelho',
  'Ritápolis',
  'Rochedo de Minas',
  'Rodeiro',
  'Romaria',
  'Rosário da Limeira',
  'Rubelita',
  'Rubim',
  'Sabará',
  'Sabinópolis',
  'Sacramento',
  'Salinas',
  'Salto da Divisa',
  'Santa Bárbara',
  'Santa Bárbara do Leste',
  'Santa Bárbara do Monte Verde',
  'Santa Bárbara do Tugúrio',
  'Santa Cruz de Minas',
  'Santa Cruz de Salinas',
  'Santa Cruz do Escalvado',
  'Santa Efigênia de Minas',
  'Santa Fé de Minas',
  'Santa Helena de Minas',
  'Santa Juliana',
  'Santa Luzia',
  'Santa Margarida',
  'Santa Maria de Itabira',
  'Santa Maria do Salto',
  'Santa Maria do Suaçuí',
  'Santa Rita de Caldas',
  'Santa Rita de Ibitipoca',
  'Santa Rita de Jacutinga',
  'Santa Rita de Minas',
  'Santa Rita do Itueto',
  'Santa Rita do Sapucaí',
  'Santa Rosa da Serra',
  'Santa Vitória',
  'Santana da Vargem',
  'Santana de Cataguases',
  'Santana de Pirapama',
  'Santana do Deserto',
  'Santana do Garambéu',
  'Santana do Jacaré',
  'Santana do Manhuaçu',
  'Santana do Paraíso',
  'Santana do Riacho',
  'Santana dos Montes',
  'Santo Antônio do Amparo',
  'Santo Antônio do Aventureiro',
  'Santo Antônio do Grama',
  'Santo Antônio do Itambé',
  'Santo Antônio do Jacinto',
  'Santo Antônio do Monte',
  'Santo Antônio do Retiro',
  'Santo Antônio do Rio Abaixo',
  'Santo Hipólito',
  'Santos Dumont',
  'São Bento Abade',
  'São Brás do Suaçuí',
  'São Domingos das Dores',
  'São Domingos do Prata',
  'São Félix de Minas',
  'São Francisco',
  'São Francisco de Paula',
  'São Francisco de Sales',
  'São Francisco do Glória',
  'São Geraldo',
  'São Geraldo da Piedade',
  'São Geraldo do Baixio',
  'São Gonçalo do Abaeté',
  'São Gonçalo do Pará',
  'São Gonçalo do Rio Abaixo',
  'São Gonçalo do Rio Preto',
  'São Gonçalo do Sapucaí',
  'São Gotardo',
  'São João Batista do Glória',
  'São João da Lagoa',
  'São João da Mata',
  'São João da Ponte',
  'São João das Missões',
  'São João del Rei',
  'São João do Manhuaçu',
  'São João do Manteninha',
  'São João do Oriente',
  'São João do Pacuí',
  'São João do Paraíso',
  'São João Evangelista',
  'São João Nepomuceno',
  'São Joaquim de Bicas',
  'São José da Barra',
  'São José da Lapa',
  'São José da Safira',
  'São José da Varginha',
  'São José do Alegre',
  'São José do Divino',
  'São José do Goiabal',
  'São José do Jacuri',
  'São José do Mantimento',
  'São Lourenço',
  'São Miguel do Anta',
  'São Pedro da União',
  'São Pedro do Suaçuí',
  'São Pedro dos Ferros',
  'São Romão',
  'São Roque de Minas',
  'São Sebastião da Bela Vista',
  'São Sebastião da Vargem Alegre',
  'São Sebastião do Anta',
  'São Sebastião do Maranhão',
  'São Sebastião do Oeste',
  'São Sebastião do Paraíso',
  'São Sebastião do Rio Preto',
  'São Sebastião do Rio Verde',
  'São Tiago',
  'São Tomás de Aquino',
  'São Tomé das Letras',
  'São Vicente de Minas',
  'Sapucaí-Mirim',
  'Sardoá',
  'Sarzedo',
  'Sem-Peixe',
  'Senador Amaral',
  'Senador Cortes',
  'Senador Firmino',
  'Senador José Bento',
  'Senador Modestino Gonçalves',
  'Senhora de Oliveira',
  'Senhora do Porto',
  'Senhora dos Remédios',
  'Sericita',
  'Seritinga',
  'Serra Azul de Minas',
  'Serra da Saudade',
  'Serra do Salitre',
  'Serra dos Aimorés',
  'Serrania',
  'Serranópolis de Minas',
  'Serranos',
  'Serro',
  'Sete Lagoas',
  'Setubinha',
  'Silveirânia',
  'Silvianópolis',
  'Simão Pereira',
  'Simonésia',
  'Sobrália',
  'Soledade de Minas',
  'Tabuleiro',
  'Taiobeiras',
  'Taparuba',
  'Tapira',
  'Tapiraí',
  'Taquaraçu de Minas',
  'Tarumirim',
  'Teixeiras',
  'Teófilo Otoni',
  'Timóteo',
  'Tiradentes',
  'Tiros',
  'Tocantins',
  'Tocos do Moji',
  'Toledo',
  'Tombos',
  'Três Corações',
  'Três Marias',
  'Três Pontas',
  'Tumiritinga',
  'Tupaciguara',
  'Turmalina',
  'Turvolândia',
  'Ubá',
  'Ubaí',
  'Ubaporanga',
  'Uberaba',
  'Uberlândia',
  'Umburatiba',
  'Unaí',
  'União de Minas',
  'Uruana de Minas',
  'Urucânia',
  'Urucuia',
  'Vargem Alegre',
  'Vargem Bonita',
  'Vargem Grande do Rio Pardo',
  'Varginha',
  'Varjão de Minas',
  'Várzea da Palma',
  'Varzelândia',
  'Vazante',
  'Verdelândia',
  'Veredinha',
  'Veríssimo',
  'Vermelho Novo',
  'Vespasiano',
  'Viçosa',
  'Vieiras',
  'Virgem da Lapa',
  'Virgínia',
  'Virginópolis',
  'Virgolândia',
  'Visconde do Rio Branco',
  'Volta Grande',
  'Wenceslau Braz',
] as const;

export const microrregioesMg = [
  { nome: 'Aimorés', cidades: [
    'Aimorés',
    'Alvarenga',
    'Conceição de Ipanema',
    'Conselheiro Pena',
    'Cuparaque',
    'Goiabeira',
    'Ipanema',
    'Itueta',
    'Mutum',
    'Pocrane',
    'Resplendor',
    'Santa Rita do Itueto',
    'Taparuba',
  ] },
  { nome: 'Alfenas', cidades: [
    'Alfenas',
    'Alterosa',
    'Areado',
    'Carmo do Rio Claro',
    'Carvalhópolis',
    'Conceição da Aparecida',
    'Divisa Nova',
    'Fama',
    'Machado',
    'Paraguaçu',
    'Poço Fundo',
    'Serrania',
  ] },
  { nome: 'Almenara', cidades: [
    'Almenara',
    'Bandeira',
    'Divisópolis',
    'Felisburgo',
    'Jacinto',
    'Jequitinhonha',
    'Joaíma',
    'Jordânia',
    'Mata Verde',
    'Monte Formoso',
    'Palmópolis',
    'Rio do Prado',
    'Rubim',
    'Salto da Divisa',
    'Santa Maria do Salto',
    'Santo Antônio do Jacinto',
  ] },
  { nome: 'Andrelândia', cidades: [
    'Aiuruoca',
    'Andrelândia',
    'Arantina',
    'Bocaina de Minas',
    'Bom Jardim de Minas',
    'Carvalhos',
    'Cruzília',
    'Liberdade',
    'Minduri',
    'Passa Vinte',
    'São Vicente de Minas',
    'Seritinga',
    'Serranos',
  ] },
  { nome: 'Araçuaí', cidades: [
    'Araçuaí',
    'Caraí',
    'Coronel Murta',
    'Itinga',
    'Novo Cruzeiro',
    'Padre Paraíso',
    'Ponto dos Volantes',
    'Virgem da Lapa',
  ] },
  { nome: 'Araxá', cidades: [
    'Araxá',
    'Campos Altos',
    'Ibiá',
    'Nova Ponte',
    'Pedrinópolis',
    'Perdizes',
    'Pratinha',
    'Sacramento',
    'Santa Juliana',
    'Tapira',
  ] },
  { nome: 'Barbacena', cidades: [
    'Alfredo Vasconcelos',
    'Antônio Carlos',
    'Barbacena',
    'Barroso',
    'Capela Nova',
    'Caranaíba',
    'Carandaí',
    'Desterro do Melo',
    'Ibertioga',
    'Ressaquinha',
    'Santa Bárbara do Tugúrio',
    'Senhora dos Remédios',
  ] },
  { nome: 'Belo Horizonte', cidades: [
    'Belo Horizonte',
    'Betim',
    'Brumadinho',
    'Caeté',
    'Confins',
    'Contagem',
    'Esmeraldas',
    'Ibirité',
    'Igarapé',
    'Juatuba',
    'Lagoa Santa',
    'Mário Campos',
    'Mateus Leme',
    'Nova Lima',
    'Pedro Leopoldo',
    'Raposos',
    'Ribeirão das Neves',
    'Rio Acima',
    'Sabará',
    'Santa Luzia',
    'São Joaquim de Bicas',
    'São José da Lapa',
    'Sarzedo',
    'Vespasiano',
  ] },
  { nome: 'Bocaiúva', cidades: [
    'Bocaiúva',
    'Engenheiro Navarro',
    'Francisco Dumont',
    'Guaraciama',
    'Olhos-d\'Água',
  ] },
  { nome: 'Bom Despacho', cidades: [
    'Araújos',
    'Bom Despacho',
    'Dores do Indaiá',
    'Estrela do Indaiá',
    'Japaraíba',
    'Lagoa da Prata',
    'Leandro Ferreira',
    'Luz',
    'Martinho Campos',
    'Moema',
    'Quartel Geral',
    'Serra da Saudade',
  ] },
  { nome: 'Campo Belo', cidades: [
    'Aguanil',
    'Campo Belo',
    'Cana Verde',
    'Candeias',
    'Cristais',
    'Perdões',
    'Santana do Jacaré',
  ] },
  { nome: 'Capelinha', cidades: [
    'Angelândia',
    'Aricanduva',
    'Berilo',
    'Capelinha',
    'Carbonita',
    'Chapada do Norte',
    'Francisco Badaró',
    'Itamarandiba',
    'Jenipapo de Minas',
    'José Gonçalves de Minas',
    'Leme do Prado',
    'Minas Novas',
    'Turmalina',
    'Veredinha',
  ] },
  { nome: 'Caratinga', cidades: [
    'Bom Jesus do Galho',
    'Bugre',
    'Caratinga',
    'Córrego Novo',
    'Dom Cavati',
    'Entre Folhas',
    'Iapu',
    'Imbé de Minas',
    'Inhapim',
    'Ipaba',
    'Piedade de Caratinga',
    'Pingo-d\'Água',
    'Santa Bárbara do Leste',
    'Santa Rita de Minas',
    'São Domingos das Dores',
    'São João do Oriente',
    'São Sebastião do Anta',
    'Tarumirim',
    'Ubaporanga',
    'Vargem Alegre',
  ] },
  { nome: 'Cataguases', cidades: [
    'Além Paraíba',
    'Argirita',
    'Cataguases',
    'Dona Euzébia',
    'Estrela Dalva',
    'Itamarati de Minas',
    'Laranjal',
    'Leopoldina',
    'Palma',
    'Pirapetinga',
    'Recreio',
    'Santana de Cataguases',
    'Santo Antônio do Aventureiro',
    'Volta Grande',
  ] },
  { nome: 'Conceição do Mato Dentro', cidades: [
    'Alvorada de Minas',
    'Conceição do Mato Dentro',
    'Congonhas do Norte',
    'Dom Joaquim',
    'Itambé do Mato Dentro',
    'Morro do Pilar',
    'Passabém',
    'Rio Vermelho',
    'Santo Antônio do Itambé',
    'Santo Antônio do Rio Abaixo',
    'São Sebastião do Rio Preto',
    'Serra Azul de Minas',
    'Serro',
  ] },
  { nome: 'Conselheiro Lafaiete', cidades: [
    'Casa Grande',
    'Catas Altas da Noruega',
    'Congonhas',
    'Conselheiro Lafaiete',
    'Cristiano Otoni',
    'Desterro de Entre Rios',
    'Entre Rios de Minas',
    'Itaverava',
    'Ouro Branco',
    'Queluzito',
    'Santana dos Montes',
    'São Brás do Suaçuí',
  ] },
  { nome: 'Curvelo', cidades: [
    'Augusto de Lima',
    'Buenópolis',
    'Corinto',
    'Curvelo',
    'Felixlândia',
    'Inimutaba',
    'Joaquim Felício',
    'Monjolos',
    'Morro da Garça',
    'Presidente Juscelino',
    'Santo Hipólito',
  ] },
  { nome: 'Diamantina', cidades: [
    'Couto de Magalhães de Minas',
    'Datas',
    'Diamantina',
    'Felício dos Santos',
    'Gouveia',
    'Presidente Kubitschek',
    'São Gonçalo do Rio Preto',
    'Senador Modestino Gonçalves',
  ] },
  { nome: 'Divinópolis', cidades: [
    'Carmo do Cajuru',
    'Cláudio',
    'Conceição do Pará',
    'Divinópolis',
    'Igaratinga',
    'Itaúna',
    'Nova Serrana',
    'Perdigão',
    'Santo Antônio do Monte',
    'São Gonçalo do Pará',
    'São Sebastião do Oeste',
  ] },
  { nome: 'Formiga', cidades: [
    'Arcos',
    'Camacho',
    'Córrego Fundo',
    'Formiga',
    'Itapecerica',
    'Pains',
    'Pedra do Indaiá',
    'Pimenta',
  ] },
  { nome: 'Frutal', cidades: [
    'Campina Verde',
    'Carneirinho',
    'Comendador Gomes',
    'Fronteira',
    'Frutal',
    'Itapagipe',
    'Iturama',
    'Limeira do Oeste',
    'Pirajuba',
    'Planura',
    'São Francisco de Sales',
    'União de Minas',
  ] },
  { nome: 'Governador Valadares', cidades: [
    'Alpercata',
    'Campanário',
    'Capitão Andrade',
    'Coroaci',
    'Divino das Laranjeiras',
    'Engenheiro Caldas',
    'Fernandes Tourinho',
    'Frei Inocêncio',
    'Galiléia',
    'Governador Valadares',
    'Itambacuri',
    'Itanhomi',
    'Jampruca',
    'Marilac',
    'Mathias Lobato',
    'Nacip Raydan',
    'Nova Módica',
    'Pescador',
    'São Geraldo da Piedade',
    'São Geraldo do Baixio',
    'São José da Safira',
    'São José do Divino',
    'Sobrália',
    'Tumiritinga',
    'Virgolândia',
  ] },
  { nome: 'Grão Mogol', cidades: [
    'Botumirim',
    'Cristália',
    'Grão Mogol',
    'Itacambira',
    'Josenópolis',
    'Padre Carvalho',
  ] },
  { nome: 'Guanhães', cidades: [
    'Braúnas',
    'Carmésia',
    'Coluna',
    'Divinolândia de Minas',
    'Dores de Guanhães',
    'Gonzaga',
    'Guanhães',
    'Materlândia',
    'Paulistas',
    'Sabinópolis',
    'Santa Efigênia de Minas',
    'São João Evangelista',
    'Sardoá',
    'Senhora do Porto',
    'Virginópolis',
  ] },
  { nome: 'Ipatinga', cidades: [
    'Açucena',
    'Antônio Dias',
    'Belo Oriente',
    'Coronel Fabriciano',
    'Ipatinga',
    'Jaguaraçu',
    'Joanésia',
    'Marliéria',
    'Mesquita',
    'Naque',
    'Periquito',
    'Santana do Paraíso',
    'Timóteo',
  ] },
  { nome: 'Itabira', cidades: [
    'Alvinópolis',
    'Barão de Cocais',
    'Bela Vista de Minas',
    'Bom Jesus do Amparo',
    'Catas Altas',
    'Dionísio',
    'Ferros',
    'Itabira',
    'João Monlevade',
    'Nova Era',
    'Nova União',
    'Rio Piracicaba',
    'Santa Bárbara',
    'Santa Maria de Itabira',
    'São Domingos do Prata',
    'São Gonçalo do Rio Abaixo',
    'São José do Goiabal',
    'Taquaraçu de Minas',
  ] },
  { nome: 'Itaguara', cidades: [
    'Belo Vale',
    'Bonfim',
    'Crucilândia',
    'Itaguara',
    'Itatiaiuçu',
    'Jeceaba',
    'Moeda',
    'Piedade dos Gerais',
    'Rio Manso',
  ] },
  { nome: 'Itajubá', cidades: [
    'Brazópolis',
    'Consolação',
    'Cristina',
    'Delfim Moreira',
    'Dom Viçoso',
    'Itajubá',
    'Maria da Fé',
    'Marmelópolis',
    'Paraisópolis',
    'Piranguçu',
    'Piranguinho',
    'Virgínia',
    'Wenceslau Braz',
  ] },
  { nome: 'Ituiutaba', cidades: [
    'Cachoeira Dourada',
    'Capinópolis',
    'Gurinhatã',
    'Ipiaçu',
    'Ituiutaba',
    'Santa Vitória',
  ] },
  { nome: 'Janaúba', cidades: [
    'Catuti',
    'Espinosa',
    'Gameleiras',
    'Jaíba',
    'Janaúba',
    'Mamonas',
    'Mato Verde',
    'Monte Azul',
    'Nova Porteirinha',
    'Pai Pedro',
    'Porteirinha',
    'Riacho dos Machados',
    'Serranópolis de Minas',
  ] },
  { nome: 'Januária', cidades: [
    'Bonito de Minas',
    'Chapada Gaúcha',
    'Cônego Marinho',
    'Icaraí de Minas',
    'Itacarambi',
    'Januária',
    'Juvenília',
    'Manga',
    'Matias Cardoso',
    'Miravânia',
    'Montalvânia',
    'Pedras de Maria da Cruz',
    'Pintópolis',
    'São Francisco',
    'São João das Missões',
    'Urucuia',
  ] },
  { nome: 'Juiz de Fora', cidades: [
    'Aracitaba',
    'Belmiro Braga',
    'Bias Fortes',
    'Bicas',
    'Chácara',
    'Chiador',
    'Coronel Pacheco',
    'Descoberto',
    'Ewbank da Câmara',
    'Goianá',
    'Guarará',
    'Juiz de Fora',
    'Lima Duarte',
    'Mar de Espanha',
    'Maripá de Minas',
    'Matias Barbosa',
    'Olaria',
    'Oliveira Fortes',
    'Paiva',
    'Pedro Teixeira',
    'Pequeri',
    'Piau',
    'Rio Novo',
    'Rio Preto',
    'Rochedo de Minas',
    'Santa Bárbara do Monte Verde',
    'Santa Rita de Ibitipoca',
    'Santa Rita de Jacutinga',
    'Santana do Deserto',
    'Santos Dumont',
    'São João Nepomuceno',
    'Senador Cortes',
    'Simão Pereira',
  ] },
  { nome: 'Lavras', cidades: [
    'Carrancas',
    'Ijaci',
    'Ingaí',
    'Itumirim',
    'Itutinga',
    'Lavras',
    'Luminárias',
    'Nepomuceno',
    'Ribeirão Vermelho',
  ] },
  { nome: 'Manhuaçu', cidades: [
    'Abre Campo',
    'Alto Caparaó',
    'Alto Jequitibá',
    'Caparaó',
    'Caputira',
    'Chalé',
    'Durandé',
    'Lajinha',
    'Luisburgo',
    'Manhuaçu',
    'Manhumirim',
    'Martins Soares',
    'Matipó',
    'Pedra Bonita',
    'Reduto',
    'Santa Margarida',
    'Santana do Manhuaçu',
    'São João do Manhuaçu',
    'São José do Mantimento',
    'Simonésia',
  ] },
  { nome: 'Mantena', cidades: [
    'Central de Minas',
    'Itabirinha',
    'Mantena',
    'Mendes Pimentel',
    'Nova Belém',
    'São Félix de Minas',
    'São João do Manteninha',
  ] },
  { nome: 'Montes Claros', cidades: [
    'Brasília de Minas',
    'Campo Azul',
    'Capitão Enéas',
    'Claro dos Poções',
    'Coração de Jesus',
    'Francisco Sá',
    'Glaucilândia',
    'Ibiracatu',
    'Japonvar',
    'Juramento',
    'Lontra',
    'Luislândia',
    'Mirabela',
    'Montes Claros',
    'Patis',
    'Ponto Chique',
    'São João da Lagoa',
    'São João da Ponte',
    'São João do Pacuí',
    'Ubaí',
    'Varzelândia',
    'Verdelândia',
  ] },
  { nome: 'Muriaé', cidades: [
    'Antônio Prado de Minas',
    'Barão do Monte Alto',
    'Caiana',
    'Carangola',
    'Divino',
    'Espera Feliz',
    'Eugenópolis',
    'Faria Lemos',
    'Fervedouro',
    'Miradouro',
    'Miraí',
    'Muriaé',
    'Orizânia',
    'Patrocínio do Muriaé',
    'Pedra Dourada',
    'Rosário da Limeira',
    'São Francisco do Glória',
    'São Sebastião da Vargem Alegre',
    'Tombos',
    'Vieiras',
  ] },
  { nome: 'Nanuque', cidades: [
    'Águas Formosas',
    'Bertópolis',
    'Carlos Chagas',
    'Crisólita',
    'Fronteira dos Vales',
    'Machacalis',
    'Nanuque',
    'Santa Helena de Minas',
    'Serra dos Aimorés',
    'Umburatiba',
  ] },
  { nome: 'Oliveira', cidades: [
    'Bom Sucesso',
    'Carmo da Mata',
    'Carmópolis de Minas',
    'Ibituruna',
    'Oliveira',
    'Passa Tempo',
    'Piracema',
    'Santo Antônio do Amparo',
    'São Francisco de Paula',
  ] },
  { nome: 'Ouro Preto', cidades: [
    'Diogo de Vasconcelos',
    'Itabirito',
    'Mariana',
    'Ouro Preto',
  ] },
  { nome: 'Pará de Minas', cidades: [
    'Florestal',
    'Onça de Pitangui',
    'Pará de Minas',
    'Pitangui',
    'São José da Varginha',
  ] },
  { nome: 'Paracatu', cidades: [
    'Brasilândia de Minas',
    'Guarda-Mor',
    'João Pinheiro',
    'Lagamar',
    'Lagoa Grande',
    'Paracatu',
    'Presidente Olegário',
    'São Gonçalo do Abaeté',
    'Varjão de Minas',
    'Vazante',
  ] },
  { nome: 'Passos', cidades: [
    'Alpinópolis',
    'Bom Jesus da Penha',
    'Capetinga',
    'Capitólio',
    'Cássia',
    'Claraval',
    'Delfinópolis',
    'Fortaleza de Minas',
    'Ibiraci',
    'Itaú de Minas',
    'Passos',
    'Pratápolis',
    'São João Batista do Glória',
    'São José da Barra',
  ] },
  { nome: 'Patos de Minas', cidades: [
    'Arapuá',
    'Carmo do Paranaíba',
    'Guimarânia',
    'Lagoa Formosa',
    'Matutina',
    'Patos de Minas',
    'Rio Paranaíba',
    'Santa Rosa da Serra',
    'São Gotardo',
    'Tiros',
  ] },
  { nome: 'Patrocínio', cidades: [
    'Abadia dos Dourados',
    'Coromandel',
    'Cruzeiro da Fortaleza',
    'Douradoquara',
    'Estrela do Sul',
    'Grupiara',
    'Iraí de Minas',
    'Monte Carmelo',
    'Patrocínio',
    'Romaria',
    'Serra do Salitre',
  ] },
  { nome: 'Peçanha', cidades: [
    'Água Boa',
    'Cantagalo',
    'Frei Lagonegro',
    'José Raydan',
    'Peçanha',
    'Santa Maria do Suaçuí',
    'São José do Jacuri',
    'São Pedro do Suaçuí',
    'São Sebastião do Maranhão',
  ] },
  { nome: 'Pedra Azul', cidades: [
    'Cachoeira de Pajeú',
    'Comercinho',
    'Itaobim',
    'Medina',
    'Pedra Azul',
  ] },
  { nome: 'Pirapora', cidades: [
    'Buritizeiro',
    'Ibiaí',
    'Jequitaí',
    'Lagoa dos Patos',
    'Lassance',
    'Pirapora',
    'Riachinho',
    'Santa Fé de Minas',
    'São Romão',
    'Várzea da Palma',
  ] },
  { nome: 'Piuí', cidades: [
    'Bambuí',
    'Córrego Danta',
    'Doresópolis',
    'Iguatama',
    'Medeiros',
    'Piumhi',
    'São Roque de Minas',
    'Tapiraí',
    'Vargem Bonita',
  ] },
  { nome: 'Poços de Caldas', cidades: [
    'Albertina',
    'Andradas',
    'Bandeira do Sul',
    'Botelhos',
    'Caldas',
    'Campestre',
    'Ibitiúra de Minas',
    'Inconfidentes',
    'Jacutinga',
    'Monte Sião',
    'Ouro Fino',
    'Poços de Caldas',
    'Santa Rita de Caldas',
  ] },
  { nome: 'Ponte Nova', cidades: [
    'Acaiaca',
    'Barra Longa',
    'Dom Silvério',
    'Guaraciaba',
    'Jequeri',
    'Oratórios',
    'Piedade de Ponte Nova',
    'Ponte Nova',
    'Raul Soares',
    'Rio Casca',
    'Rio Doce',
    'Santa Cruz do Escalvado',
    'Santo Antônio do Grama',
    'São Pedro dos Ferros',
    'Sem-Peixe',
    'Sericita',
    'Urucânia',
    'Vermelho Novo',
  ] },
  { nome: 'Pouso Alegre', cidades: [
    'Bom Repouso',
    'Borda da Mata',
    'Bueno Brandão',
    'Camanducaia',
    'Cambuí',
    'Congonhal',
    'Córrego do Bom Jesus',
    'Espírito Santo do Dourado',
    'Estiva',
    'Extrema',
    'Gonçalves',
    'Ipuiúna',
    'Itapeva',
    'Munhoz',
    'Pouso Alegre',
    'Sapucaí-Mirim',
    'Senador Amaral',
    'Senador José Bento',
    'Tocos do Moji',
    'Toledo',
  ] },
  { nome: 'Salinas', cidades: [
    'Águas Vermelhas',
    'Berizal',
    'Curral de Dentro',
    'Divisa Alegre',
    'Fruta de Leite',
    'Indaiabira',
    'Montezuma',
    'Ninheira',
    'Novorizonte',
    'Rio Pardo de Minas',
    'Rubelita',
    'Salinas',
    'Santa Cruz de Salinas',
    'Santo Antônio do Retiro',
    'São João do Paraíso',
    'Taiobeiras',
    'Vargem Grande do Rio Pardo',
  ] },
  { nome: 'Santa Rita do Sapucaí', cidades: [
    'Cachoeira de Minas',
    'Careaçu',
    'Conceição das Pedras',
    'Conceição dos Ouros',
    'Cordislândia',
    'Heliodora',
    'Natércia',
    'Pedralva',
    'Santa Rita do Sapucaí',
    'São Gonçalo do Sapucaí',
    'São João da Mata',
    'São José do Alegre',
    'São Sebastião da Bela Vista',
    'Silvianópolis',
    'Turvolândia',
  ] },
  { nome: 'São João Del Rei', cidades: [
    'Conceição da Barra de Minas',
    'Coronel Xavier Chaves',
    'Dores de Campos',
    'Lagoa Dourada',
    'Madre de Deus de Minas',
    'Nazareno',
    'Piedade do Rio Grande',
    'Prados',
    'Resende Costa',
    'Ritápolis',
    'Santa Cruz de Minas',
    'Santana do Garambéu',
    'São João del Rei',
    'São Tiago',
    'Tiradentes',
  ] },
  { nome: 'São Lourenço', cidades: [
    'Alagoa',
    'Baependi',
    'Cambuquira',
    'Carmo de Minas',
    'Caxambu',
    'Conceição do Rio Verde',
    'Itamonte',
    'Itanhandu',
    'Jesuânia',
    'Lambari',
    'Olímpio Noronha',
    'Passa Quatro',
    'Pouso Alto',
    'São Lourenço',
    'São Sebastião do Rio Verde',
    'Soledade de Minas',
  ] },
  { nome: 'São Sebastião do Paraíso', cidades: [
    'Arceburgo',
    'Cabo Verde',
    'Guaranésia',
    'Guaxupé',
    'Itamogi',
    'Jacuí',
    'Juruaia',
    'Monte Belo',
    'Monte Santo de Minas',
    'Muzambinho',
    'Nova Resende',
    'São Pedro da União',
    'São Sebastião do Paraíso',
    'São Tomás de Aquino',
  ] },
  { nome: 'Sete Lagoas', cidades: [
    'Araçaí',
    'Baldim',
    'Cachoeira da Prata',
    'Caetanópolis',
    'Capim Branco',
    'Cordisburgo',
    'Fortuna de Minas',
    'Funilândia',
    'Inhaúma',
    'Jaboticatubas',
    'Jequitibá',
    'Maravilhas',
    'Matozinhos',
    'Papagaios',
    'Paraopeba',
    'Pequi',
    'Prudente de Morais',
    'Santana de Pirapama',
    'Santana do Riacho',
    'Sete Lagoas',
  ] },
  { nome: 'Teófilo Otoni', cidades: [
    'Ataléia',
    'Catuji',
    'Franciscópolis',
    'Frei Gaspar',
    'Itaipé',
    'Ladainha',
    'Malacacheta',
    'Novo Oriente de Minas',
    'Ouro Verde de Minas',
    'Pavão',
    'Poté',
    'Setubinha',
    'Teófilo Otoni',
  ] },
  { nome: 'Três Marias', cidades: [
    'Abaeté',
    'Biquinhas',
    'Cedro do Abaeté',
    'Morada Nova de Minas',
    'Paineiras',
    'Pompéu',
    'Três Marias',
  ] },
  { nome: 'Ubá', cidades: [
    'Astolfo Dutra',
    'Divinésia',
    'Dores do Turvo',
    'Guarani',
    'Guidoval',
    'Guiricema',
    'Mercês',
    'Piraúba',
    'Rio Pomba',
    'Rodeiro',
    'São Geraldo',
    'Senador Firmino',
    'Silveirânia',
    'Tabuleiro',
    'Tocantins',
    'Ubá',
    'Visconde do Rio Branco',
  ] },
  { nome: 'Uberaba', cidades: [
    'Água Comprida',
    'Campo Florido',
    'Conceição das Alagoas',
    'Conquista',
    'Delta',
    'Uberaba',
    'Veríssimo',
  ] },
  { nome: 'Uberlândia', cidades: [
    'Araguari',
    'Araporã',
    'Canápolis',
    'Cascalho Rico',
    'Centralina',
    'Indianópolis',
    'Monte Alegre de Minas',
    'Prata',
    'Tupaciguara',
    'Uberlândia',
  ] },
  { nome: 'Unaí', cidades: [
    'Arinos',
    'Bonfinópolis de Minas',
    'Buritis',
    'Cabeceira Grande',
    'Dom Bosco',
    'Formoso',
    'Natalândia',
    'Unaí',
    'Uruana de Minas',
  ] },
  { nome: 'Varginha', cidades: [
    'Boa Esperança',
    'Campanha',
    'Campo do Meio',
    'Campos Gerais',
    'Carmo da Cachoeira',
    'Coqueiral',
    'Elói Mendes',
    'Guapé',
    'Ilicínea',
    'Monsenhor Paulo',
    'Santana da Vargem',
    'São Bento Abade',
    'São Tomé das Letras',
    'Três Corações',
    'Três Pontas',
    'Varginha',
  ] },
  { nome: 'Viçosa', cidades: [
    'Alto Rio Doce',
    'Amparo do Serra',
    'Araponga',
    'Brás Pires',
    'Cajuri',
    'Canaã',
    'Cipotânea',
    'Coimbra',
    'Ervália',
    'Lamim',
    'Paula Cândido',
    'Pedra do Anta',
    'Piranga',
    'Porto Firme',
    'Presidente Bernardes',
    'Rio Espera',
    'São Miguel do Anta',
    'Senhora de Oliveira',
    'Teixeiras',
    'Viçosa',
  ] },
] as const;
